import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
import AppErrorBoundary from './AppErrorBoundary'
import WebAccessGate from './WebAccessGate'
import { installAuthorizedFetch } from './api'
import './style.css'
import './analysis.css'
import './scanner.css'
import './radar.css'
import './consensus.css'
import './paper.css'
import './live.css'
import './guard.css'
import './risk.css'
import './adaptive.css'
import './lab.css'
import './gate.css'
import './journal.css'
import './freshness.css'
import './liquidity.css'
import './system.css'
import './archive.css'
import './command.css'
import './v4.css'
import './v5.css'
import './v6.css'
import './v7.css'
import './v8.css'
import './v9.css'
import './v10.css'
import './v11.css'
import './v11_1.css'
import './v12.css'
import './v20.css'
import './binance-demo.css'
import './modern-fusion.css'
import './commercial.css'
import './commerce-v24.css'
import './execution-v25.css'
import './web-access.css'

installAuthorizedFetch()
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><AppErrorBoundary><WebAccessGate><App/></WebAccessGate></AppErrorBoundary></React.StrictMode>)
